// Code generated by MockGen. DO NOT EDIT.
// Source: pr_service.go
//
// Generated by this command:
//
//	mockgen -source=pr_service.go -destination=../mocks/pr_service.go -package=mocks .
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pr-service/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, team *models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, team)
}

// GetByID mocks base method.
func (m *MockTeamRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockTeamRepository) GetByName(ctx context.Context, name string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTeamRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTeamRepository)(nil).GetByName), ctx, name)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// GetActiveByTeam mocks base method.
func (m *MockUserRepository) GetActiveByTeam(ctx context.Context, teamID uuid.UUID) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByTeam", ctx, teamID)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByTeam indicates an expected call of GetActiveByTeam.
func (mr *MockUserRepositoryMockRecorder) GetActiveByTeam(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByTeam", reflect.TypeOf((*MockUserRepository)(nil).GetActiveByTeam), ctx, teamID)
}

// GetByTeam mocks base method.
func (m *MockUserRepository) GetByTeam(ctx context.Context, teamID uuid.UUID) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTeam", ctx, teamID)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTeam indicates an expected call of GetByTeam.
func (mr *MockUserRepositoryMockRecorder) GetByTeam(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTeam", reflect.TypeOf((*MockUserRepository)(nil).GetByTeam), ctx, teamID)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, id)
}

// UpdateActive mocks base method.
func (m *MockUserRepository) UpdateActive(ctx context.Context, id uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActive indicates an expected call of UpdateActive.
func (mr *MockUserRepositoryMockRecorder) UpdateActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActive", reflect.TypeOf((*MockUserRepository)(nil).UpdateActive), ctx, id, active)
}

// MockPRRepository is a mock of PRRepository interface.
type MockPRRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPRRepositoryMockRecorder
	isgomock struct{}
}

// MockPRRepositoryMockRecorder is the mock recorder for MockPRRepository.
type MockPRRepositoryMockRecorder struct {
	mock *MockPRRepository
}

// NewMockPRRepository creates a new mock instance.
func NewMockPRRepository(ctrl *gomock.Controller) *MockPRRepository {
	mock := &MockPRRepository{ctrl: ctrl}
	mock.recorder = &MockPRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRRepository) EXPECT() *MockPRRepositoryMockRecorder {
	return m.recorder
}

// AssignReviewers mocks base method.
func (m *MockPRRepository) AssignReviewers(ctx context.Context, prID uuid.UUID, reviewers []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignReviewers", ctx, prID, reviewers)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignReviewers indicates an expected call of AssignReviewers.
func (mr *MockPRRepositoryMockRecorder) AssignReviewers(ctx, prID, reviewers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignReviewers", reflect.TypeOf((*MockPRRepository)(nil).AssignReviewers), ctx, prID, reviewers)
}

// Create mocks base method.
func (m *MockPRRepository) Create(ctx context.Context, pr *models.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPRRepositoryMockRecorder) Create(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPRRepository)(nil).Create), ctx, pr)
}

// GetByID mocks base method.
func (m *MockPRRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPRRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPRRepository)(nil).GetByID), ctx, id)
}

// ListByReviewer mocks base method.
func (m *MockPRRepository) ListByReviewer(ctx context.Context, id uuid.UUID) ([]*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReviewer", ctx, id)
	ret0, _ := ret[0].([]*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReviewer indicates an expected call of ListByReviewer.
func (mr *MockPRRepositoryMockRecorder) ListByReviewer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReviewer", reflect.TypeOf((*MockPRRepository)(nil).ListByReviewer), ctx, id)
}

// Merge mocks base method.
func (m *MockPRRepository) Merge(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockPRRepositoryMockRecorder) Merge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPRRepository)(nil).Merge), ctx, id)
}

// ReplaceReviewer mocks base method.
func (m *MockPRRepository) ReplaceReviewer(ctx context.Context, prID, oldID, newID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceReviewer", ctx, prID, oldID, newID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceReviewer indicates an expected call of ReplaceReviewer.
func (mr *MockPRRepositoryMockRecorder) ReplaceReviewer(ctx, prID, oldID, newID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceReviewer", reflect.TypeOf((*MockPRRepository)(nil).ReplaceReviewer), ctx, prID, oldID, newID)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManager)(nil).Do), ctx, fn)
}
